# Generated by Django 2.2.5 on 2019-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aviable',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
    ]
