# Generated by Django 2.2.5 on 2019-09-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product_aviable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
